# Generated by Django 4.2.20 on 2025-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="original_url",
            field=models.URLField(db_index=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
