# Generated by Django 4.2.20 on 2025-04-11 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_alter_tag_unique_together"),
        ("news", "0002_news_original_url_alter_author_name_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="news.author",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="news", to="tags.tag"
            ),
        ),
    ]
