# Generated by Django 4.2.20 on 2025-04-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "type")},
        ),
    ]
